CREATE TABLE Friendships (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    User1Id UNIQUEIDENTIFIER NOT NULL,
    User2Id UNIQUEIDENTIFIER NOT NULL,
    CreatedAt DATETIME2 NOT NULL,

    CONSTRAINT FK_Friendships_User1 FOREIGN KEY (User1Id) REFERENCES Users(Id),
    CONSTRAINT FK_Friendships_User2 FOREIGN KEY (User2Id) REFERENCES Users(Id),
    
);


